### ISSUE TITLE
Bot not starting up

### ISSUE THREAD

**Issue by cherryblossom2020** [ihasTaco/ChatDSA#2]
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    openai.api_key = os.environ["REDACTED"]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'REDACTED'

Not sure what is causing this error.

**Comment by ihasTaco** [comment]
You need to add the api key to an environment variable on your computer with the name OPENAI_API_KEY and your api key as the value, google "how to add environment variables <your OS>" if you don't know how

Or if you don't want to use environment variables you can change this line from this

openai.api_key = os.environ["OPENAI_API_KEY"]

To this 

openai.api_key = "your api key"

It'll work just fine either way, but if it's for production use I would recommend using the environment variables

**Comment by ihasTaco** [comment]
And also same thing for the discord token, add a new environment variable "CHATDSA_TOKEN" and the value will be the discord token,

Or change this line from this

client.run(os.environ["CHATDSA_TOKEN"])

To this

client.run("discord token")

**Comment by cherryblossom2020** [comment]
Thank you
